# Copyright 2026 The mini-electron Authors
# Use of this source code is governed by the Apache-2.0 license.

assert(is_mac, "Use python build.py for the native Windows build backend.")

group("default") {
  deps = [
    "//build/macos:mini_electron_browser",
    "//build/macos:mini_electron",
    "//build/macos:mini_electron_smoke",
  ]
}
